name: 更新金榜年终奖助力码

on:
  workflow_dispatch:
  schedule:
    - cron: '47 6,9,18 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_updateSplit
jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false 
          fetch-depth: 0
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: npm install
        run: |
          npm install
      - name: '运行 【更新金榜年终奖助力码】'
        run: |
          node jd_updateSplit.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
      - name: commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "update by Action" -a || echo "Nothing to update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: master
      - name: Purge CDN Cache
        run: curl https://purge.jsdelivr.net/gh/DX3242/updateTeam@master/shareCodes/split.json           
